[package]
name = "cargo-test-changed"
version = "0.1.0"
edition = "2021"
description = "A Cargo subcommand to run tests for changed crates and their dependents"

[dependencies]
anyhow = "1.0"
cargo_metadata = "0.15"
clap = { version = "4.5.34", features = ["derive"] }
gix = { version = "0.70", features = ["status"] }
indexmap = "2.8.0"
itertools = "0.14.0"
serde = { version = "1.0", features = ["derive"] }

[[bin]]
name = "cargo-test-changed"
path = "src/main.rs"
